{"version":"3.10.1","messages":["\nAn error occurred while loading ./spec/models/author_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  RSpec.describe Author, type: :model do\u001b[0m\n\u001b[31m    it \"can be created with valid data\" do\u001b[0m\n\u001b[31m      author = Author.new(name: \"Caligula\", phone_number: \"5553054425\")\u001b[0m\n\u001b[31m      expect(author).to be_valid\u001b[0m\n\u001b[31m    end\u001b[0m\n\u001b[31m    \u001b[0m\n\u001b[31m    describe 'Basic validations' do\u001b[0m\n\u001b[31m      it { is_expected.to validate_presence_of :name }\u001b[0m\n\u001b[31m      it { is_expected.to validate_uniqueness_of :name }\u001b[0m\n\u001b[31m      it { is_expected.to validate_length_of(:phone_number).is_equal_to(10) }\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mSyntaxError:\u001b[0m\n\u001b[31m  /Users/jennman/Development/code/phase-4/phase-4-active-record-validations-lab/app/models/author.rb:3: syntax error, unexpected integer literal, expecting =\u003e\u001b[0m\n\u001b[31m  ... presence: true,length: {:is 10}\u001b[0m\n\u001b[31m  ...                             ^~\u001b[0m\n\u001b[36m# /Users/jennman/.rvm/gems/ruby-2.7.4/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'\u001b[0m\n\u001b[36m# /Users/jennman/.rvm/gems/ruby-2.7.4/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'\u001b[0m\n\u001b[36m# ./spec/models/author_spec.rb:3:in `\u003ctop (required)\u003e'\u001b[0m\n"],"examples":[],"summary":{"duration":2.9e-05,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":1},"summary_line":"0 examples, 0 failures, 1 error occurred outside of examples"}